# Generated by Django 5.1 on 2024-08-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.EmailField(max_length=100, verbose_name='email')),
                ('following', models.EmailField(max_length=100, verbose_name='email')),
                ('is_live', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'follow',
                'indexes': [models.Index(fields=['follower'], name='follow_followe_227ce4_idx'), models.Index(fields=['following'], name='follow_followi_9fea95_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='follower-following')],
            },
        ),
    ]
